-- ==========================================
-- CRM Supabase Backend Setup Script
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Create the `leads` table
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Primary key, auto-increment
    name TEXT NOT NULL CHECK (char_length(trim(name)) > 0), -- Required, cannot be empty
    email TEXT NOT NULL CHECK (char_length(trim(email)) > 0), -- Required, cannot be empty
    source TEXT,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'converted')),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL -- Default to now()
);

-- 2. Enable Row Level Security (RLS)
-- ------------------------------------------
-- By default, this restricts all access unless a policy grants it.
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies for Authenticated Users Only
-- ------------------------------------------

-- Allow SELECT: Authenticated users can read all leads
CREATE POLICY "Allow SELECT only for authenticated users" 
ON public.leads 
FOR SELECT 
TO authenticated 
USING (true);

-- Allow INSERT: Authenticated users can insert new leads
CREATE POLICY "Allow INSERT only for authenticated users" 
ON public.leads 
FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Allow UPDATE: Authenticated users can update any lead
CREATE POLICY "Allow UPDATE only for authenticated users" 
ON public.leads 
FOR UPDATE 
TO authenticated 
USING (true);

-- Allow DELETE: Authenticated users can delete any lead
CREATE POLICY "Allow DELETE only for authenticated users" 
ON public.leads 
FOR DELETE 
TO authenticated 
USING (true);

-- ==========================================
-- 4. TEST DATABASE
-- ==========================================

-- Insert sample lead manually
-- Note: Replace this with an authenticated insert via frontend or run this assuming a bypass if doing it in the raw SQL editor
INSERT INTO public.leads (name, email, source, status, notes)
VALUES ('John Doe', 'john.doe@example.com', 'Website', 'new', 'Looking for CRM services.');

-- Update status from 'new' to 'contacted'
UPDATE public.leads
SET status = 'contacted'
WHERE email = 'john.doe@example.com';

-- Delete a record
DELETE FROM public.leads
WHERE email = 'john.doe@example.com';

-- Verify all operations work correctly by viewing the table
SELECT * FROM public.leads;

-- ==========================================
-- 5. Create the `support_messages` table
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS public.support_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    email TEXT,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Enable Row Level Security (RLS)
-- ------------------------------------------
ALTER TABLE public.support_messages ENABLE ROW LEVEL SECURITY;

-- 7. Create RLS Policies for support_messages
-- ------------------------------------------

-- Allow INSERT: Anyone can send a message (e.g. from the website contact form)
CREATE POLICY "Allow anyone to insert messages" 
ON public.support_messages 
FOR INSERT 
WITH CHECK (true);

-- Allow ALL: Only admins can view and manage messages
-- We check for the 'role' field inside user_metadata
CREATE POLICY "Allow admins to manage all messages" 
ON public.support_messages 
FOR ALL
TO authenticated
USING ( (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin' );

